# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: BUPT nCov Auto

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 16 * * *'
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipreqs
        pipreqs .
        pip install -r requirements.txt
    - name: 'signin'
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        AREA: ${{ secrets.AREA }}
        PUSHDEER: ${{ secrets.PUSHDEER }}
      run: python main.py

